### ISSUE TITLE
Implement highlighting for annotations.

### ISSUE THREAD

**Issue by bfan1256** [Biblink/biblink-frontend#22]
Add highlighting of the annotations as created in the sketch design. An image of the design is below:

<img width="50%" style="margin: 0 auto;" alt="screen shot 2018-06-11 at 11 48 51 pm" src="https://user-images.githubusercontent.com/15917894/41269219-0a647f9c-6dd2-11e8-80f4-d505f8405060.png">

**Comment by bfan1256** [comment]
Current status is that first part is that highlighting works, however, @jfan1256 still needs to display the number of annotations and the two most recent posts' authors images as per the specifications above.

**Comment by jfan1256** [comment]
Fixed in latest commit [75e440b](https://github.com/Biblink/biblink-frontend/commit/75e440b11301e0a6927eca0245004953483b0e74)
